apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xfejlktcp-python 
  janus-idp.io/tekton: xfejlktcp-python
  backstage.io/kubernetes-id: xfejlktcp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xfejlktcp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml